from __future__ import annotations

from .models import CommandSpec

COMMAND_SPECS: tuple[CommandSpec, ...] = (
    CommandSpec(
        name="robinhood_get_accounts",
        aliases=("get_accounts",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="List brokerage accounts.",
    ),
    CommandSpec(
        name="robinhood_get_portfolio",
        aliases=("get_portfolio",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Portfolio value and performance metrics.",
    ),
    CommandSpec(
        name="robinhood_get_positions",
        aliases=("get_positions", "get_equity_positions"),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Current stock holdings.",
    ),
    CommandSpec(
        name="robinhood_get_position",
        aliases=("get_position",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Single stock holding by ticker.",
    ),
    CommandSpec(
        name="robinhood_get_watchlist",
        aliases=("get_watchlist",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Named watchlist contents.",
    ),
    CommandSpec(
        name="robinhood_get_quote",
        aliases=("get_quote", "get_equity_quotes"),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Underlying quote lookup.",
    ),
    CommandSpec(
        name="robinhood_get_fundamentals",
        aliases=("get_fundamentals",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Fundamental equity data.",
    ),
    CommandSpec(
        name="robinhood_get_historicals",
        aliases=("get_historicals",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Historical price data.",
    ),
    CommandSpec(
        name="robinhood_get_news",
        aliases=("get_news",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Recent stock news.",
    ),
    CommandSpec(
        name="robinhood_get_earnings",
        aliases=("get_earnings",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Earnings dates and estimates.",
    ),
    CommandSpec(
        name="robinhood_get_ratings",
        aliases=("get_ratings",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Analyst ratings summary.",
    ),
    CommandSpec(
        name="robinhood_get_dividends",
        aliases=("get_dividends",),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Dividend payment history.",
    ),
    CommandSpec(
        name="robinhood_get_options_positions",
        aliases=("get_options_positions", "get_option_positions"),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Current option holdings.",
    ),
    CommandSpec(
        name="robinhood_get_order_history",
        aliases=("get_order_history", "get_equity_orders"),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Stock order history and status.",
    ),
    CommandSpec(
        name="robinhood_search_symbols",
        aliases=("search", "search_symbols"),
        category="research_read",
        support_tier="verified_public_source",
        route="public_mcp_read",
        summary="Search stocks by ticker or company name.",
    ),
    CommandSpec(
        name="create_order_draft",
        category="active_trading_preview",
        support_tier="local_beta_delegate",
        route="chatgpt_delegate",
        approval_policy="operator_confirm_required",
        summary="Approval-gated order draft preview.",
        notes=("Local beta supports draft intent, not autonomous live submission.",),
    ),
    CommandSpec(
        name="order_draft",
        category="active_trading_preview",
        support_tier="local_beta_delegate",
        route="chatgpt_delegate",
        approval_policy="operator_confirm_required",
        summary="Delegate order draft handoff.",
    ),
    CommandSpec(
        name="order_submit",
        category="active_trading_write",
        support_tier="local_beta_delegate",
        route="chatgpt_delegate",
        approval_policy="operator_confirm_required",
        summary="Delegate live-order style request behind explicit approval.",
    ),
    CommandSpec(
        name="order_cancel",
        category="active_trading_write",
        support_tier="local_beta_delegate",
        route="chatgpt_delegate",
        approval_policy="operator_confirm_required",
        summary="Delegate cancel request behind explicit approval.",
    ),
    CommandSpec(
        name="order_replace",
        category="active_trading_write",
        support_tier="local_beta_delegate",
        route="chatgpt_delegate",
        approval_policy="operator_confirm_required",
        summary="Delegate replace request behind explicit approval.",
    ),
    CommandSpec(
        name="create_watchlist",
        category="custom_logic_candidate",
        support_tier="implemented_custom_logic",
        route="custom_logic_local",
        handler_name="create_watchlist",
        summary="Create a local SharpEdge workflow-state watchlist queue.",
        notes=(
            "This is implemented as local SharpEdge bridge logic.",
            "It does not claim verified public Robinhood watchlist-write support.",
        ),
    ),
    CommandSpec(
        name="update_watchlist",
        category="custom_logic_candidate",
        support_tier="custom_logic_candidate",
        route="custom_logic_required",
        summary="Candidate for custom watchlist update logic.",
        notes=("Covers rename/edit style watchlist actions.",),
    ),
    CommandSpec(
        name="get_watchlists",
        category="custom_logic_candidate",
        support_tier="custom_logic_candidate",
        route="custom_logic_required",
        summary="Candidate for watchlist directory/list-all logic.",
    ),
    CommandSpec(
        name="get_option_watchlist",
        category="custom_logic_candidate",
        support_tier="custom_logic_candidate",
        route="custom_logic_required",
        summary="Candidate for option-specific watchlist logic.",
    ),
    CommandSpec(
        name="get_option_chains",
        category="custom_logic_candidate",
        support_tier="custom_logic_candidate",
        route="custom_logic_required",
        summary="Candidate for option-chain lookup logic.",
    ),
    CommandSpec(
        name="get_option_instruments",
        category="custom_logic_candidate",
        support_tier="custom_logic_candidate",
        route="custom_logic_required",
        summary="Candidate for individual option-contract lookup logic.",
    ),
    CommandSpec(
        name="get_equity_tradability",
        category="custom_logic_candidate",
        support_tier="custom_logic_candidate",
        route="custom_logic_required",
        summary="Candidate for tradability-eligibility logic.",
    ),
)


def find_command_spec(candidate: str) -> CommandSpec | None:
    for spec in COMMAND_SPECS:
        if spec.matches(candidate):
            return spec
    return None
